### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ehn** [Makin-Things/weather-radar-card#13]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I installed using HACS (leave unchecked for manual installs)

**Release with the issue:**
v2.0.5

**Last working release (if known):**
This is the first version I've tried.

**Browser and Operating System:**
* 102.0.5005.61 (Official Build) (x86_64)
* macOS 12.4

**Card Config (click Show Code Editor and copy paste your config, remove a few of the least significant digits of your lat/lon to avoid posting you exact home address):**

type: custom:weather-radar-card
card_title: Weather radar
data_source: RainViewer-Original
map_style: Voyager
zoom_level: 7
show_marker: true
show_scale: true
show_zoom: true
show_playback: true
show_range: true
square_map: false
show_recenter: false
extra_labels: true

**Description of problem:**

I'm seeing this error message in the logs:

```
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 9:07:16 AM (1 occurrences)
Last logged: 9:07:16 AM

http://10.1.2.1:8123/hacsfiles/weather-radar-card/weather-radar-card.js?hacstag=487680971205:1246:887 Uncaught TypeError: Cannot delete property 'map_style' of #<Object>
```

**Javascript errors shown in the web inspector (if applicable):**

```
weather-radar-card.js?hacstag=487680971205:1291   WEATHER-RADAR-CARD   Version 2.0.5    
frigate-hass-card.js?hacstag=394082552300:21563   FRIGATE-HASS-CARD   Version 3.0.0    
plotly-graph-card.js?hacstag=413812496131:12  PLOTLY-GRAPH  1.3.1 production
weather-radar-card.js?hacstag=487680971205:1246 Uncaught TypeError: Cannot delete property 'map_style' of #<Object>
    at Xn._valueChangedString (weather-radar-card.js?hacstag=487680971205:1246:887)
    at Z.handleEvent (weather-radar-card.js?hacstag=487680971205:17:7353)
    at Object.notifySelected (mwc-list-base.ts:270:1)
    at E.setSingleSelectionAtIndex_ (5d3d20ff.js:2:8387)
    at E.setSelectedIndexOnAction_ (5d3d20ff.js:2:10920)
    at E.handleSingleSelection (5d3d20ff.js:2:7176)
    at b.onRequestSelected (mwc-list-base.ts:270:1)
    at F.handleEvent (styles.ts:369:1)
    at mwc-list-item.fireRequestSelected (weather-radar-card.js?hacstag=487680971205:506:382)
    at mwc-list-item.onClick (weather-radar-card.js?hacstag=487680971205:506:22)
:8123/energy:1 Uncaught (in promise) Object
weather?edit=1:1 Autofocus processing was blocked because a document already has a focused element.
:8123/energy:1 Uncaught (in promise) Object
DevTools failed to load source map: Could not load content for http://10.1.2.1:8123/local/community/weather-radar-card/leaflet.js.map: Fetch through target failed: Frame not found; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Additional information:**

**Comment by Makin-Things** [comment]
I have been unable to reproduce this error, but while hunting for it found another possible cause of an exception which I have published a pre-release to fix (2.0.6b1). I don't think it will fix your issue though, but could you test it.

The point in the code that your exception came from was within the gui editor, but from your log it looked like you where just starting HA when it occurred. Is this correct?

**Comment by ehn** [comment]
Whether it's what you did or something else, I don't know, but I upgraded to 2.0.6b1, and I'm no longer getting that error message. Not in the log, nor in the console.

However, when I open the JavaScript console, I'm getting this error:

```
DevTools failed to load source map: Could not load content for http://10.1.2.1:8123/local/community/weather-radar-card/leaflet.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

When I go to that URL in the browser, I'm also getting a `404: Not Found`. Maybe this is a separate issue?

**Comment by Makin-Things** [comment]
I'll be honest, I don't think the change that I made should have fixed the error you saw, but glad it is fixed.

The devtool error is just because I didn't bother including the map file, it only helps with debugging, but in the case of this card where most/all of the work occurs in an iframe it really doesn't help. It is something that can be ignored and you will only ever see it in the dev mode console of a browser.

**Comment by Makin-Things** [comment]
I'll push this update as a proper release in about a weeks time, to try and catch a few bugs if any are found.

**Comment by ehn** [comment]
Will monitor and let you know if the issue resurfaces.

Other things I did which may or may not have had an impact:

* Upgrade Home Assistant from 2022.6.2 to 2022.6.3
* Restart HA

**Comment by Makin-Things** [comment]
Assuming the update fixed this. Please re-open if this is not the case.

**Comment by ehn** [comment]
Haven't seen the issue since. Seems fixed. Thanks!
