### ISSUE TITLE
HACS installation not possible: reports "No Releases or Repo Not Found" 

### ISSUE THREAD

**Issue by wralb** [Makin-Things/weather-radar-card#2]
**Checklist:**

- [ ] I updated to the latest version available
- [x] I cleared the cache of my browser
- [ ] I installed using HACS (leave unchecked for manual installs)

**Release with the issue:**
v2.0.2
**Last working release (if known):**
N/A
**Browser and Operating System:**
Firefox / Windows 10
**Card Config (click Show Code Editor and copy paste your config, remove a few of the least significant digits of your lat/lon to avoid posting you exact home address):**
N/A

**Description of problem:**
"Weather Radar Card" appears as new repository in HACS, but installation is not possible as HACS reports "No Releases or Repo Not Found"
Manual installation works fine; really love this card.

![image](https://user-images.githubusercontent.com/47241942/167566890-b0e87bee-1c6e-498b-9a2d-bf5929d40e95.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Environment information:
![image](https://user-images.githubusercontent.com/47241942/167568216-8747fb4b-417d-458d-af7b-48e36e7308d7.png)

**Comment by Makin-Things** [comment]
github has been randomly deleting releases which is causing this issue. It is also happening to other people. I have a request in to github to try and get it resolved.

**Comment by wralb** [comment]
Thanks for the info. 
Hope Github sort it soon :)

**Comment by Makin-Things** [comment]
Apparently github have acknowledged the problem and are working on it.
In the meantime v2.0.3 has been released (for now).

**Comment by wralb** [comment]
Great.  I was able to manually install 2.03 earlier today.  Now I have been able to do a re-install with HACS. All is working well. Thanks for all your work on this really useful card.
