### ISSUE TITLE
Card flickers on HA 2022-11

### ISSUE THREAD

**Issue by ielbury** [Makin-Things/weather-radar-card#22]
Is anyone having an issue with the radar card flickering/reloading when the starting the sequence of radar images? 

This card worked with the last version, 2022-10 but exhibited this problem after updating to 2022-11.

For me, the problem is on Chrome, Edge and Firefox. Cleared the cache in all and no change.

My config is:

type: custom:weather-radar-card
data_source: RainViewer-Original
show_zoom: true
show_marker: false
static_map: false
show_playback: false
square_map: false
extra_labels: false
show_scale: false
show_range: false
zoom_level: 8
show_recenter: true

It's on a Panel (1 card) view.

Video of the problem in OneDrive https://1drv.ms/u/s!ArXzPwEK-0K_nYx3AL4yK0EmiYvZwQ?e=sC219g

**Comment by Makin-Things** [comment]
Can you please test a pre-release 2.1.1 that hopefully fixes this. It is caused by the brain dead decision to reduce card size real estate by 2px in height/width by adding those stupid borders.

**Comment by ielbury** [comment]
Installed 2.1.1 and it looks good.

Thanks for the awesome product!
