### ISSUE TITLE
Set default latitude and longitude options to the home assistant location.

### ISSUE THREAD

**Issue by wralb** [Makin-Things/weather-radar-card#3]
**Is your feature request related to a problem? Please describe.**
Initial setup would have been slightly faster and easier if the `center_latitude` and `center_longitude` options defaulted to the home location of my home assistant installation.  This could also mean that the centre of the map adjusted automatically if the home zone was changed.  This might make adoptions experience better for new users.

**Describe the solution you'd like**
Set defaults for `center_latitude`, `center_longitude`, `marker_latitude` and `marker_longitude` to be the location of the "home zone".  This might be retrieved from the latitude and longitude attributes of `zone.home`.

**Describe alternatives you've considered**
Thinking about idea #1 from robbinonline, a more complex solution might be to implement his idea and change the example configuration to use `zone.home`.

**Comment by Makin-Things** [comment]
This has been done in 2.0.3.

**Comment by wralb** [comment]
Thanks. This enhancement works perfectly in 2.0.3.
