### ISSUE TITLE
Add a card title

### ISSUE THREAD

**Issue by Jefe2** [Makin-Things/weather-radar-card#4]
I am adding multiple radar cards.  It would be a nice enhancement to allow card titles to differentiate the cards.

**Comment by Makin-Things** [comment]
Could you post a mock up of how you think it should look?
I have tried to limit the number of controls etc that cover potentially more useful radar information.

**Comment by Jefe2** [comment]
This is only a suggestion. I can use a markdown card as well. Here is what I using:

<img width="491" alt="Weather-Radar-Card" src="https://user-images.githubusercontent.com/47016097/167855037-5e20a92e-d2a9-4386-a865-f3c39d03abc8.png">

**Comment by Makin-Things** [comment]
I will think about this, but that looks rather ugly and takes up a bunch of space. I do agree though that there should be some way to label a card. I have some other cards that I have multiple of that only I know the location for them.

**Comment by Makin-Things** [comment]
@Jefe2 this is now currently being worked on. I hopefully will have a beta release in the next day.

**Comment by Makin-Things** [comment]
V2.0.4 has been released that includes this option.
