### ISSUE TITLE
Time Zone setting

### ISSUE THREAD

**Issue by michl270** [Makin-Things/weather-radar-card#5]
First of all: Thanks for that great Weather Radar Card :-)

I am using my Home Assistant instance in Germany and therefore, my timezone setting in Home Assistant is GMT+1

Having installed the card via HACS, I am wondering which time zone is used in the card at the bottom:
![2022-05-13 09_40_04-Übersicht – Home Assistant](https://user-images.githubusercontent.com/75853405/168235269-caf8f75b-cf7c-4be9-a7c4-22f91a316ebb.png)

Would it be possible to change the timezone according to the Home Assistant server settings?

**Comment by Makin-Things** [comment]
It should be using whatever local time on your system gives.
I am a little confused as an hour or so ago (when you opened this issue) the time in Germany was roughly 9am so that time looks about right. What time were you expecting to see?

**Comment by Makin-Things** [comment]
@michl270 did you resolve this?

**Comment by michl270** [comment]
Hi @Makin-Things,
Thanks very much for your fast reply. My assumption is, that the radar shows predictive information.
I have set the frame count to 25. The loop always ends at my current local time. Please see attached video:
https://user-images.githubusercontent.com/75853405/168548837-5a77de87-9689-4383-9950-78598bf72959.mp4

Thanks for your assistance :-)

**Comment by Makin-Things** [comment]
No radar loops are not predictive. They show actual radar images as captured by meteorological radars. So generally the loop will finish 5-10 minutes before you local time. Basically they show what is really happening.

**Comment by michl270** [comment]
Ok - thanks for the information. Knowing that, everything is working as designed and expected.
