### ISSUE TITLE
Question: integrate with HA ootb map func.

### ISSUE THREAD

**Issue by vingerha** [Makin-Things/weather-radar-card#6]
Hi, I am a happy user of your work, was thinking if there is more to do with that and came to the idea on integrating the functionality that the default/ootb map of HA provides. I am not (!) asking for  feature but merely trying to find out how much effort (or maybe also a directon on how to) would be involved to add person(location) and zone

**Comment by Makin-Things** [comment]
Sorry but Home Assistant itself doesn't expose and functionality to all the addition of custom layers to the ootb map. I previously looked at possibly doing that and it can't be done.
